import { SoknadApi } from '../../../../../services/minesykmeldte/schema/soknad'
import { PeriodeEnum } from '../../../../queries/graphql.generated'
import { SoknadSporsmalKriterierEnum, SoknadSporsmalSvartypeEnum, SporsmalTagEnum } from '../../../resolvers.generated'

export const utenlandsk1: SoknadApi = {
    id: 'c03b166b-062c-4ba7-9f87-fc28a7bfafd0',
    sykmeldingId: '5a035f23-a7be-469a-9c24-bf6492c45d7e',
    fom: '2022-01-03',
    tom: '2022-01-10',
    navn: 'navn',
    fnr: '12345678912',
    lest: false,
    sendtDato: '2022-03-16T09:39:39.633876919',
    sendtTilNavDato: null,
    korrigererSoknadId: null,
    perioder: [
        { fom: '2022-01-03', tom: '2022-01-10', sykmeldingsgrad: 100, sykmeldingstype: PeriodeEnum.AktivitetIkkeMulig },
    ],
    sporsmal: [
        {
            id: '1660548',
            tag: SporsmalTagEnum.FravarForSykmeldingen,
            min: null,
            max: null,
            sporsmalstekst:
                'Var du syk og borte fra jobb før du ble sykmeldt, i perioden 18. desember 2021 - 2. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660549',
                    tag: SporsmalTagEnum.FravarForSykmeldingenNar,
                    min: '2021-07-03',
                    max: '2022-01-02',
                    sporsmalstekst:
                        'Hvilke dager var du syk og borte fra jobb, før du ble sykmeldt? Du trenger bare oppgi dager før 3. januar 2022.',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Perioder,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660522',
            tag: SporsmalTagEnum.TilbakeIArbeid,
            min: null,
            max: null,
            sporsmalstekst:
                'Var du tilbake i fullt arbeid hos PENGELØS SPAREBANK i løpet av perioden 3. - 10. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660523',
                    tag: SporsmalTagEnum.TilbakeNar,
                    min: '2022-01-03',
                    max: '2022-01-10',
                    sporsmalstekst: 'Når begynte du å jobbe igjen?',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Dato,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660524',
            tag: SporsmalTagEnum.FerieV2,
            min: null,
            max: null,
            sporsmalstekst: 'Hadde du ferie i tidsrommet 3. - 10. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660525',
                    tag: SporsmalTagEnum.FerieNarV2,
                    min: '2022-01-03',
                    max: '2022-01-10',
                    sporsmalstekst: 'Når tok du ut ferie?',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Perioder,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660526',
            tag: SporsmalTagEnum.PermisjonV2,
            min: null,
            max: null,
            sporsmalstekst: 'Tok du permisjon mens du var sykmeldt 3. - 10. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660527',
                    tag: SporsmalTagEnum.PermisjonNarV2,
                    min: '2022-01-03',
                    max: '2022-01-10',
                    sporsmalstekst: 'Når tok du permisjon?',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Perioder,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660528',
            tag: SporsmalTagEnum.UtlandV2,
            min: null,
            max: null,
            sporsmalstekst: 'Var du på reise utenfor EØS mens du var sykmeldt 3. - 10. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660529',
                    tag: SporsmalTagEnum.UtlandNarV2,
                    min: '2022-01-03',
                    max: '2022-01-10',
                    sporsmalstekst: 'Når var du utenfor EØS?',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Perioder,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660555',
            tag: SporsmalTagEnum.JobbetDu_100Prosent,
            min: null,
            max: null,
            sporsmalstekst:
                'I perioden 3. - 10. januar 2022 var du 100 % sykmeldt fra PENGELØS SPAREBANK. Jobbet du noe i denne perioden?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660556',
                    tag: SporsmalTagEnum.HvorMangeTimerPerUke,
                    min: '1',
                    max: '150',
                    sporsmalstekst:
                        'Hvor mange timer i uken jobber du vanligvis når du er frisk? Varierer det, kan du oppgi gjennomsnittet.',
                    undertekst: 'timer per uke',
                    svartype: SoknadSporsmalSvartypeEnum.Tall,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
                {
                    id: '1660557',
                    tag: SporsmalTagEnum.HvorMyeHarDuJobbet,
                    min: null,
                    max: null,
                    sporsmalstekst: 'Hvor mye jobbet du tilsammen 3. - 10. januar 2022?',
                    undertekst: 'Velg timer eller prosent',
                    svartype: SoknadSporsmalSvartypeEnum.RadioGruppeTimerProsent,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [
                        {
                            id: '1660558',
                            tag: SporsmalTagEnum.HvorMyeTimer,
                            min: null,
                            max: null,
                            sporsmalstekst: 'Timer',
                            undertekst: null,
                            svartype: SoknadSporsmalSvartypeEnum.Radio,
                            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Checked,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '1660559',
                                    tag: SporsmalTagEnum.HvorMyeTimerVerdi,
                                    min: '1',
                                    max: '171',
                                    sporsmalstekst: null,
                                    undertekst: 'timer totalt',
                                    svartype: SoknadSporsmalSvartypeEnum.Tall,
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                },
                            ],
                        },
                        {
                            id: '1660560',
                            tag: SporsmalTagEnum.HvorMyeProsent,
                            min: null,
                            max: null,
                            sporsmalstekst: 'Prosent',
                            undertekst: null,
                            svartype: SoknadSporsmalSvartypeEnum.Radio,
                            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Checked,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '1660561',
                                    tag: SporsmalTagEnum.HvorMyeProsentVerdi,
                                    min: '1',
                                    max: '99',
                                    sporsmalstekst: null,
                                    undertekst: 'prosent',
                                    svartype: SoknadSporsmalSvartypeEnum.Tall,
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            id: '1660551',
            tag: SporsmalTagEnum.PermittertNaa,
            min: null,
            max: null,
            sporsmalstekst: 'Var du permittert av arbeidsgiveren din da du ble sykmeldt 3. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660552',
                    tag: SporsmalTagEnum.PermittertNaaNar,
                    min: '2020-02-01',
                    max: '2022-01-10',
                    sporsmalstekst: 'Velg første dag i permitteringen',
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Dato,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
        {
            id: '1660553',
            tag: SporsmalTagEnum.PermittertPeriode,
            min: null,
            max: null,
            sporsmalstekst:
                'Har du vært permittert av arbeidsgiveren din i mer enn 14 sammenhengende dager mellom 3. desember 2021 - 3. januar 2022?',
            undertekst: null,
            svartype: SoknadSporsmalSvartypeEnum.JaNei,
            kriterieForVisningAvUndersporsmal: SoknadSporsmalKriterierEnum.Ja,
            svar: [{ verdi: 'NEI' }],
            undersporsmal: [
                {
                    id: '1660554',
                    tag: SporsmalTagEnum.PermittertPeriodeNar,
                    min: '2021-12-03',
                    max: '2022-01-03',
                    sporsmalstekst: null,
                    undertekst: null,
                    svartype: SoknadSporsmalSvartypeEnum.Perioder,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                },
            ],
        },
    ],
}
