allowBuilds:
  '@apollo/protobufjs': false
  '@parcel/watcher': true
  lefthook: true
  protobufjs: false
  sharp: true

minimumReleaseAge: 4320
blockExoticSubdeps: true

overrides:
  brace-expansion: 5.0.6
  immutable: 3.8.3
  js-cookie: 3.0.6
  lodash: 4.18.1
  protobufjs: 8.2.0
