allowBuilds:
  '@apollo/protobufjs': false
  '@parcel/watcher': true
  lefthook: true
  protobufjs: false
  sharp: true
overrides:
  form-data: 4.0.4
  sha.js: 2.4.12
  '@graphql-codegen/cli>graphql-config': 5.1.6
  minimatch: 9.0.9
  rollup: 4.60.0
  immutable: 3.8.3
  picomatch: 4.0.4
  micromatch>picomatch: 2.3.2
  yaml: 2.8.3
  brace-expansion: 5.0.5
