apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/arbeidsgiver/sykmeldte-esyfo'
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  idporten:
    enabled: true
    sidecar:
      enabled: true
      resources:
        requests:
          cpu: 100m
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 400m
      memory: 756Mi
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dinesykmeldte-backend
          namespace: team-esyfo
        - application: nav-dekoratoren
          namespace: personbruker
  liveness:
    path: /arbeidsgiver/sykmeldte-esyfo/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte-esyfo/api/internal/is_ready
  startup:
    path: /arbeidsgiver/sykmeldte-esyfo/api/internal/is_ready
    initialDelay: 20
  env:
    - name: RUNTIME_VERSION
      value: {{version}}
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: prod-gcp:team-esyfo:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: http://dinesykmeldte-backend.team-esyfo
