apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
    branchState: {{branchState}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas}}
    max: {{replicas}}
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  liveness:
    path: /arbeidsgiver/sykmeldte-esyfo/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte-esyfo/api/internal/is_ready
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  env:
    - name: RUNTIME_VERSION
      value: demo
