apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/arbeidsgiver/sykmeldte'
  prometheus:
    enabled: true
    path: /arbeidsgiver/sykmeldte/api/internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  idporten:
    enabled: true
    sidecar:
      enabled: true
      resources:
        requests:
          cpu: 100m
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 400m
      memory: 756Mi
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dinesykmeldte-backend
        - application: dinesykmeldte-backend
          namespace: team-esyfo
        - application: flexjar-backend
          namespace: flex
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  liveness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
  startup:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
    initialDelay: 20
  env:
    - name: RUNTIME_VERSION
      value: {{version}}
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: prod-gcp:team-esyfo:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: http://dinesykmeldte-backend.team-esyfo
    - name: FLEXJAR
      value: 'http://flexjar-backend.flex'
    - name: FLEXJAR_BACKEND_SCOPE
      value: 'prod-gcp:flex:flexjar-backend'
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamsykmelding-unleash-api.nav.cloud.nais.io/api'
  envFrom:
    - secret: dinesykmeldte-unleash-secrets
