apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.ekstern.dev.nav.no/arbeidsgiver/sykmeldte'
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  idporten:
    enabled: true
    sidecar:
      enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dinesykmeldte-backend
          namespace: team-esyfo
        - application: oppfolgingsplan-backend
          namespace: team-esyfo
        - application: nav-dekoratoren
          namespace: personbruker
  liveness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
  env:
    - name: RUNTIME_VERSION
      value: {{version}}
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: dev-gcp:team-esyfo:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: http://dinesykmeldte-backend.team-esyfo
    - name: OPPFOLGINGSPLAN_BACKEND_SCOPE
      value: dev-gcp:team-esyfo:oppfolgingsplan-backend
    - name: OPPFOLGINGSPLAN_BACKEND_URL
      value: http://oppfolgingsplan-backend
