name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  APP: dinesykmeldte
  BASE_PATH: /arbeidsgiver/sykmeldte

permissions:
  actions: read
  contents: read
  security-events: write
  packages: write
  id-token: write

jobs:
  test-and-verify:
    name: Test, lint and verify
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/yarn-cached@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn lint
      - run: yarn tsc
      - run: yarn test

  build-dev:
    name: Build for dev
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    outputs:
      image: ${{ steps.build-and-publish.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/next-to-docker@main
        id: build-and-publish
        with:
          app: ${{ env.APP }}
          env: dev
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev-main:
    name: Deploy main to dev
    environment:
      name: dev
      url: https://www.ekstern.dev.nav.no/arbeidsgiver/sykmeldte
    runs-on: ubuntu-latest
    needs: [build-dev, test-and-verify]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.build-dev.outputs.image }}

  build-demo:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'demo')
    name: Build for demo
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    outputs:
      image: ${{ steps.build-and-publish.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/next-to-docker@main
        id: build-and-publish
        with:
          app: ${{ env.APP }}
          env: demo
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-demo-main:
    if: github.ref_name == 'main'
    name: Deploy main to demo
    environment:
      name: demo-main
      url: https://${{ env.APP }}.ekstern.dev.nav.no${{ env.BASE_PATH }}
    runs-on: ubuntu-latest
    needs: [build-demo, test-and-verify]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-demo.yaml
          VAR: image=${{ needs.build-demo.outputs.image }},ingress=https://${{ env.APP }}.ekstern.dev.nav.no${{ env.BASE_PATH }},appname=${{ env.APP }},replicas=1,branchState=alive

  build-prod:
    if: github.ref_name == 'main'
    name: Build for prod
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    outputs:
      image: ${{ steps.build-and-publish.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/next-to-docker@main
        id: build-and-publish
        with:
          app: ${{ env.APP }}
          env: prod
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod-main:
    name: Deploy main to prod
    environment:
      name: prod
      url: https://www.nav.no/arbeidsgiver/sykmeldte
    runs-on: ubuntu-latest
    needs: [build-prod, test-and-verify]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          VAR: image=${{ needs.build-prod.outputs.image }}
