name: Build & Deploy
on:
  push:
    branches-ignore:
      - esyfo

permissions:
  actions: read
  contents: read
  security-events: write
  packages: write
  id-token: write

jobs:
  next-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app.yaml@main
    secrets: inherit
    with:
      app: dinesykmeldte
      base-path: /arbeidsgiver/sykmeldte
